import React, { useState, useEffect, useContext} from "react";
import { Context } from "../../context";
import Head from 'next/head';
import styles from './styles.module.scss';
import { useSwipeable } from 'react-swipeable';
import { useRouter } from 'next/router';

import {Colors, initial} from '../../components/theme_color';
import { data } from "./data";
import { Card } from "./card";



/** Academics tab */
function index() {
 const { replace} = useRouter();
 const [ theme, setTheme] = useState(initial);
 const { dispatch } = useContext(Context)


useEffect(()=> {
   setTheme(Colors())
},[])

 const handlers = useSwipeable({
   onSwiped: (eventData) => {
    const { dir} = eventData;
    if(dir === 'Left'){
       replace('/Schedule')
       dispatch({
         type: "OFFLOAD",
         payload: false
       })
    }
   },
});


  return (
    <div {...handlers}>
      <Head>
        <title>TMUC | Academics</title>
        <meta name="description" content="Generated by create next app" />
      <meta name="theme-color" content={theme?.background} />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.academic_container} style={{color: theme?.primary, backgroundColor: theme?.farground}}>
        <div className={styles.card_wrapper}>
            {data.map( i => (
              <Card key={i.name} href={i.href} name={i.name} icon={i.icon} />
            ))}
        </div>
      </div>
    </div>
  )
}

export default index;