import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import axios from "axios";
import styles from '../styles/styles.module.css';

export default function Home() {
    const [ data, setData] = useState([])
    useEffect(() => {
        // Make a request for a user with a given ID
        axios.get('/api/news')
        .then(function (response) {
            // handle success
            let news = response.data;
            let info = news?.data?.split('\n').filter(function(entry) { return /\S/.test(entry); })
            setData(info)
        })
        .catch(function (error) {
            // handle error
            console.log(error);
        })
    },[])

 data.map((i, el) =>{
     console.log(i)
 })

  return (
    <div className={styles.news}>
    <Head>
        <title>TMUC | News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <h1 className={styles.h1}>TMUC NEWS DESK</h1>
        {data?.map((el, i) => (
          <p key={i} className={styles.news_item}> - {el}</p>
        ))}
      </main>
    </div>   
  )
}